name: Update Pages

on:
  push:
    branches:
      - master  # when there is a push on 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Install Doxygen
    - name: Install Doxygen
      run: sudo apt-get install doxygen

    # Generate Doxygen doc
    - name: Generate Doxygen documentation
      run: |
        ls
        ls doc
        doxygen doc/doxyfile

    # Copy generated doc to temporary folder
    - name: Copy doc on runner
      run: cp doc/html/* ../doc/html

    # Push doc on branch 'gh-pages'
    - name: Deploy documentation to gh-pages
      run: |
        # Configure Git user to avoid authentication messages
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Switch to branch 'gh-pages'
        git checkout gh-pages

        # Copy doc to current directory
        cp -r ../doc/html/* .

        # Commit and push doc
        git add .
        git commit -m "Update Doxygen"
        git push origin gh-pages --force
