name: Update Pages

on:
  push:
    branches:
      - master  # when there is a push on 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Doxygen
    - name: Install Doxygen
      run: sudo apt-get install doxygen

    # Generate Doxygen doc
    - name: Generate Doxygen documentation
      run: |
        cd doc
        doxygen doxyfile
        cd ..

    # Copy generated doc to temporary folder
    - name: Copy doc on runner
      run: mkdir ../doc & cp -r doc/html/* ../doc

    # Push doc on branch 'gh-pages'
    - name: Deploy documentation to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_2 }}
      run: |
        # Configure Git user to avoid authentication messages
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Switch to branch 'gh-pages'
        git checkout --orphan gh-pages

        # Copy doc to current directory
        cp -r ../doc/* .

        # Commit and push doc
        git add .
        git commit -m "Update Doxygen"
        git push https://$GITHUB_ACTOR:${{ secrets.GH_PAGES_DEPLOY_2 }}@github.com/${{ github.repository }}.git gh-pages --force
